name: test-and-deploy

on:
  schedule:
    - cron: "0 * * * *"   # every hour UTC
  workflow_dispatch:      # allow manual run

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (prod only)
        run: npm run test:prod-all
        continue-on-error: true


      - name: Upload reports
        if: always()   # ✅ upload reports even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: reports/**/html-report

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: html-report
          path: reports/latest

      - name: Prepare reports folder
        run: |
          mkdir -p public/reports
          timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
          mv reports/latest public/reports/$timestamp

          # Keep only last 10 reports
          cd public/reports
          ls -t | tail -n +11 | xargs -I {} rm -rf {}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
